universe = docker
docker_image = astral/uv:debian
executable = run.sh
output = logs/lnn.$(ClusterId).$(ProcId).out
error = logs/lnn.$(ClusterId).$(ProcId).err
log = logs/lnn.$(ClusterId).$(ProcId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_memory = 64G
requirements = (GPUs_Capability >= 7.0)
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue
